var classes = [
    {
        "name": "User\\Controller\\AuthenticationController",
        "interface": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpleLoginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Core\\Controller\\ControllerAbstract",
            "Core\\Exception\\ObjectNotFoundException"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 52,
        "vocabulary": 20,
        "volume": 224.74,
        "difficulty": 4.63,
        "effort": 1039.42,
        "level": 0.22,
        "bugs": 0.07,
        "time": 58,
        "intelligentContent": 48.59,
        "number_operators": 15,
        "number_operands": 37,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 28,
        "loc": 55,
        "lloc": 27,
        "mi": 96.59,
        "mIwoC": 51.91,
        "commentWeight": 44.68,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 36.5,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 73,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "User\\Controller\\UserController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.83,
        "effort": 82.5,
        "level": 0.55,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 24.55,
        "number_operators": 4,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 8,
        "loc": 19,
        "lloc": 11,
        "mi": 107.79,
        "mIwoC": 65.57,
        "commentWeight": 42.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 16.2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "User\\Interactor\\User\\GetById",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetByIdInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "User\\Interactor\\User\\GetList",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetListInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\HomepageController",
        "interface": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 119,
        "mIwoC": 75.43,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Interactor\\GetByIdTrait",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Maghead\\Runtime\\Repo"
        ],
        "parents": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 2,
        "effort": 37.15,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.29,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 15,
        "loc": 28,
        "lloc": 13,
        "mi": 111.98,
        "mIwoC": 66.68,
        "commentWeight": 45.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Interactor\\GetListTrait",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Maghead\\Runtime\\Repo"
        ],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 14,
        "loc": 27,
        "lloc": 13,
        "mi": 112.92,
        "mIwoC": 68.01,
        "commentWeight": 44.91,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Twig\\EnvironmentFactory",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "Twig_Environment",
            "Twig_Environment",
            "App\\Twig\\Extension\\RouterExtension"
        ],
        "parents": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 9,
        "volume": 57.06,
        "difficulty": 2,
        "effort": 114.12,
        "level": 0.5,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 28.53,
        "number_operators": 4,
        "number_operands": 14,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 14,
        "loc": 30,
        "lloc": 16,
        "mi": 104.88,
        "mIwoC": 61.3,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Twig\\Extension\\RouterExtension",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFunctions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Twig_Extension",
            "Core\\Router\\UriResolverInterface",
            "Twig_Function"
        ],
        "parents": [
            "Twig_Extension"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 6,
        "volume": 20.68,
        "difficulty": 1.5,
        "effort": 31.02,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 13.79,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 14,
        "loc": 27,
        "lloc": 13,
        "mi": 111.26,
        "mIwoC": 66.35,
        "commentWeight": 44.91,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Core\\UriResolver\\UriResolverAwareTrait",
        "interface": false,
        "methods": [
            {
                "name": "getUriResolver",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUriResolver",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Router\\UriResolverInterface",
            "Core\\Router\\UriResolverInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 13,
        "loc": 26,
        "lloc": 13,
        "mi": 112.47,
        "mIwoC": 68.01,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Dispatcher",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getControllerInstance",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "QuimCalpe\\Router\\Dispatcher\\DispatcherInterface",
            "Core\\Service\\ControllerInitializer",
            "QuimCalpe\\Router\\Route\\ParsedRoute",
            "RuntimeException",
            "Core\\Controller\\ControllerAbstract"
        ],
        "parents": [],
        "lcom": 1,
        "length": 46,
        "vocabulary": 20,
        "volume": 198.81,
        "difficulty": 4.5,
        "effort": 894.64,
        "level": 0.22,
        "bugs": 0.07,
        "time": 50,
        "intelligentContent": 44.18,
        "number_operators": 10,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 25,
        "loc": 52,
        "lloc": 27,
        "mi": 96.37,
        "mIwoC": 52.41,
        "commentWeight": 43.96,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.8,
        "totalSystemComplexity": 49.8,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Router\\UriResolver",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findURI",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Router\\UriResolverInterface",
            "Core\\Router\\UriResolverInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 17,
        "loc": 30,
        "lloc": 13,
        "mi": 111.64,
        "mIwoC": 65.68,
        "commentWeight": 45.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Service\\ControllerInitializer",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Container\\ContainerAwareInterface",
            "Psr\\Container\\ContainerInterface",
            "Core\\Controller\\ControllerAbstract"
        ],
        "parents": [],
        "lcom": 2,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 2,
        "effort": 37.15,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.29,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 12,
        "loc": 25,
        "lloc": 13,
        "mi": 110.62,
        "mIwoC": 66.68,
        "commentWeight": 43.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Core\\View",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\RenderableInterface",
            "Twig_Environment"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 20,
        "loc": 33,
        "lloc": 13,
        "mi": 112.39,
        "mIwoC": 65.68,
        "commentWeight": 46.71,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Container\\ContainerAwareTrait",
        "interface": false,
        "methods": [
            {
                "name": "getContainer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContainer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "Psr\\Container\\ContainerInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 12,
        "loc": 25,
        "lloc": 13,
        "mi": 111.95,
        "mIwoC": 68.01,
        "commentWeight": 43.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Exception\\ObjectNotFoundException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 9,
        "lloc": 4,
        "mi": 216.73,
        "mIwoC": 171,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "Core\\Security\\UserAccessManagerFactory",
        "interface": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Security\\UserAccessManager",
            "Core\\Authentication\\AuthenticatorInterface",
            "Core\\Security\\UserVoterDecisionManager",
            "Core\\Security\\UserAccessManager"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 10,
        "loc": 19,
        "lloc": 9,
        "mi": 114.25,
        "mIwoC": 69.16,
        "commentWeight": 45.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Security\\UserAccessManager",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "can",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Security\\UserAccessManagerInterface",
            "Core\\Security\\UserVoteInterface",
            "User\\Model\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 16,
        "loc": 29,
        "lloc": 13,
        "mi": 111.33,
        "mIwoC": 65.68,
        "commentWeight": 45.65,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Core\\Security\\UserVoterAbstract",
        "interface": false,
        "methods": [
            {
                "name": "voteForSubjectAttributesByUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "User\\Model\\User",
            "User\\Model\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 7,
        "volume": 58.95,
        "difficulty": 3.4,
        "effort": 200.45,
        "level": 0.29,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 17.34,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 22,
        "loc": 40,
        "lloc": 18,
        "mi": 105.16,
        "mIwoC": 59.55,
        "commentWeight": 45.62,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.56,
        "relativeSystemComplexity": 5.56,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 4.67,
        "totalSystemComplexity": 16.67,
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Core\\Security\\UserVoterDecisionManager",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "vote",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVoters",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAttributes",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Core\\Security\\UserVoteInterface",
            "User\\Model\\User",
            "User\\Model\\User",
            "User\\Model\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 35,
        "vocabulary": 10,
        "volume": 116.27,
        "difficulty": 7.67,
        "effort": 891.38,
        "level": 0.13,
        "bugs": 0.04,
        "time": 50,
        "intelligentContent": 15.17,
        "number_operators": 12,
        "number_operands": 23,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 33,
        "loc": 70,
        "lloc": 37,
        "mi": 94.5,
        "mIwoC": 50.79,
        "commentWeight": 43.71,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.2,
        "relativeSystemComplexity": 17.2,
        "totalStructuralComplexity": 80,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 86,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Core\\Controller\\ControllerFactory",
        "interface": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getController",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "DI\\Definition\\Definition",
            "controllerClassName"
        ],
        "parents": [],
        "lcom": 1,
        "length": 34,
        "vocabulary": 12,
        "volume": 121.89,
        "difficulty": 4.17,
        "effort": 507.87,
        "level": 0.24,
        "bugs": 0.04,
        "time": 28,
        "intelligentContent": 29.25,
        "number_operators": 9,
        "number_operands": 25,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 17,
        "loc": 42,
        "lloc": 25,
        "mi": 96.04,
        "mIwoC": 54.36,
        "commentWeight": 41.68,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 36.5,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 73,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Controller\\ControllerAbstract",
        "interface": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "redirectToRoute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHeaderLocationAndTerminate",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Container\\ContainerAwareInterface",
            "Core\\Renderable\\RenderableAwareInterface",
            "Core\\UriResolver\\UriResolverAwareInterface"
        ],
        "parents": [],
        "lcom": 2,
        "length": 18,
        "vocabulary": 9,
        "volume": 57.06,
        "difficulty": 2.29,
        "effort": 130.42,
        "level": 0.44,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 24.96,
        "number_operators": 2,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 18,
        "loc": 39,
        "lloc": 21,
        "mi": 102.16,
        "mIwoC": 58.72,
        "commentWeight": 43.43,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 16.53,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 49.6,
        "pageRank": 0.07,
        "afferentCoupling": 9,
        "efferentCoupling": 3,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Core\\Authentication\\AuthenticationService",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIdentity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasIdentity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Core\\Authentication\\AuthenticatorInterface",
            "Core\\Authentication\\Manager\\AuthenticationManagerInterface",
            "Core\\Token\\UserTokenStorageInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 30,
        "vocabulary": 9,
        "volume": 95.1,
        "difficulty": 7.6,
        "effort": 722.74,
        "level": 0.13,
        "bugs": 0.03,
        "time": 40,
        "intelligentContent": 12.51,
        "number_operators": 11,
        "number_operands": 19,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 27,
        "loc": 56,
        "lloc": 29,
        "mi": 97.84,
        "mIwoC": 53.84,
        "commentWeight": 44,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 16.73,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 2.2,
        "totalSystemComplexity": 50.2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Authentication\\AuthenticationStatus",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 13,
        "loc": 20,
        "lloc": 7,
        "mi": 124.13,
        "mIwoC": 76.69,
        "commentWeight": 47.43,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Core\\Authentication\\Manager\\AuthenticationManager",
        "interface": false,
        "methods": [
            {
                "name": "getKeyUser",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logInUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logOutUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasUserToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Authentication\\Manager\\AuthenticationManagerInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "User\\Model\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 23,
        "vocabulary": 6,
        "volume": 59.45,
        "difficulty": 8,
        "effort": 475.63,
        "level": 0.13,
        "bugs": 0.02,
        "time": 26,
        "intelligentContent": 7.43,
        "number_operators": 7,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 32,
        "loc": 64,
        "lloc": 32,
        "mi": 99.07,
        "mIwoC": 54.61,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 49.67,
        "totalStructuralComplexity": 294,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 298,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Application",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "init",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initEnvironment",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initRouter",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initDispatcher",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initDatabase",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initSession",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "Maghead\\Runtime\\Config\\FileConfigLoader",
            "Maghead\\Runtime\\Bootstrap"
        ],
        "parents": [],
        "lcom": 1,
        "length": 77,
        "vocabulary": 35,
        "volume": 394.95,
        "difficulty": 6.1,
        "effort": 2410.59,
        "level": 0.16,
        "bugs": 0.13,
        "time": 134,
        "intelligentContent": 64.71,
        "number_operators": 18,
        "number_operands": 59,
        "number_operators_unique": 6,
        "number_operands_unique": 29,
        "cloc": 51,
        "loc": 121,
        "lloc": 70,
        "mi": 83.53,
        "mIwoC": 41.3,
        "commentWeight": 42.23,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.02,
        "relativeSystemComplexity": 196.02,
        "totalStructuralComplexity": 1568,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 1568.13,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Session",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Session\\Session"
        ],
        "parents": [
            "Symfony\\Component\\HttpFoundation\\Session\\Session"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Token\\UserTokenStorage",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserByToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAnonymousUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\Token\\UserTokenStorageInterface",
            "Maghead\\Runtime\\Repo",
            "User\\Model\\User",
            "className"
        ],
        "parents": [],
        "lcom": 2,
        "length": 12,
        "vocabulary": 6,
        "volume": 31.02,
        "difficulty": 2,
        "effort": 62.04,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 15.51,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 19,
        "loc": 37,
        "lloc": 18,
        "mi": 106.83,
        "mIwoC": 62.04,
        "commentWeight": 44.79,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Renderable\\RenderableAwareTrait",
        "interface": false,
        "methods": [
            {
                "name": "setRenderable",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Core\\RenderableInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 19,
        "lloc": 9,
        "mi": 118.52,
        "mIwoC": 73.43,
        "commentWeight": 45.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Core\\Router",
        "interface": false,
        "methods": [
            {
                "name": "loadRoutes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "QuimCalpe\\Router\\Router",
            "Core\\Router\\RouterInterface",
            "Core\\Router\\UriResolverInterface"
        ],
        "parents": [
            "QuimCalpe\\Router\\Router"
        ],
        "lcom": 1,
        "length": 21,
        "vocabulary": 12,
        "volume": 75.28,
        "difficulty": 2.83,
        "effort": 213.31,
        "level": 0.35,
        "bugs": 0.03,
        "time": 12,
        "intelligentContent": 26.57,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 12,
        "loc": 25,
        "lloc": 13,
        "mi": 106.23,
        "mIwoC": 62.29,
        "commentWeight": 43.94,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Security\\EnoughFundsToPurchaseArticleByUser",
        "interface": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Core\\Security\\UserVoterAbstract",
            "User\\Model\\User"
        ],
        "parents": [
            "Core\\Security\\UserVoterAbstract"
        ],
        "lcom": 2,
        "length": 27,
        "vocabulary": 12,
        "volume": 96.79,
        "difficulty": 4.25,
        "effort": 411.37,
        "level": 0.24,
        "bugs": 0.03,
        "time": 23,
        "intelligentContent": 22.78,
        "number_operators": 10,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 20,
        "loc": 41,
        "lloc": 21,
        "mi": 100.99,
        "mIwoC": 56.85,
        "commentWeight": 44.15,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.17,
        "relativeSystemComplexity": 6.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 4.33,
        "totalSystemComplexity": 12.33,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Security\\AccessArticleContentByUserVoter",
        "interface": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "Core\\Security\\UserVoterAbstract",
            "User\\Model\\User"
        ],
        "parents": [
            "Core\\Security\\UserVoterAbstract"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 12,
        "volume": 107.55,
        "difficulty": 4.25,
        "effort": 457.08,
        "level": 0.24,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 25.31,
        "number_operators": 13,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 28,
        "loc": 55,
        "lloc": 27,
        "mi": 98.43,
        "mIwoC": 53.74,
        "commentWeight": 44.68,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.13,
        "relativeSystemComplexity": 11.13,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 4.25,
        "totalSystemComplexity": 22.25,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Controller\\AuthorController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Core\\Controller\\ControllerAbstract",
            "Core\\Exception\\ObjectNotFoundException"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 49,
        "vocabulary": 20,
        "volume": 211.77,
        "difficulty": 4.5,
        "effort": 952.99,
        "level": 0.22,
        "bugs": 0.07,
        "time": 53,
        "intelligentContent": 47.06,
        "number_operators": 13,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 16,
        "loc": 40,
        "lloc": 24,
        "mi": 94.86,
        "mIwoC": 53.34,
        "commentWeight": 41.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 16.5,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 33,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Controller\\ArticleController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Core\\Controller\\ControllerAbstract",
            "Core\\Exception\\ObjectNotFoundException"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 49,
        "vocabulary": 20,
        "volume": 211.77,
        "difficulty": 4.5,
        "effort": 952.99,
        "level": 0.22,
        "bugs": 0.07,
        "time": 53,
        "intelligentContent": 47.06,
        "number_operators": 13,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 15,
        "loc": 39,
        "lloc": 24,
        "mi": 94.32,
        "mIwoC": 53.34,
        "commentWeight": 40.98,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Controller\\ArticlePurchaseController",
        "interface": false,
        "methods": [
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Core\\Controller\\ControllerAbstract",
            "Core\\Exception\\ObjectNotFoundException"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 76,
        "vocabulary": 25,
        "volume": 352.93,
        "difficulty": 5.33,
        "effort": 1882.31,
        "level": 0.19,
        "bugs": 0.12,
        "time": 105,
        "intelligentContent": 66.17,
        "number_operators": 20,
        "number_operands": 56,
        "number_operators_unique": 4,
        "number_operands_unique": 21,
        "cloc": 19,
        "loc": 50,
        "lloc": 31,
        "mi": 89.77,
        "mIwoC": 48.96,
        "commentWeight": 40.82,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 49.63,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 49.63,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Controller\\CategoryController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Core\\Controller\\ControllerAbstract",
            "Core\\Exception\\ObjectNotFoundException"
        ],
        "parents": [
            "Core\\Controller\\ControllerAbstract"
        ],
        "lcom": 1,
        "length": 49,
        "vocabulary": 20,
        "volume": 211.77,
        "difficulty": 4.5,
        "effort": 952.99,
        "level": 0.22,
        "bugs": 0.07,
        "time": 53,
        "intelligentContent": 47.06,
        "number_operators": 13,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 16,
        "loc": 40,
        "lloc": 24,
        "mi": 94.86,
        "mIwoC": 53.34,
        "commentWeight": 41.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 16.5,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 33,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Category\\GetById",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetByIdInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Category\\GetList",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetListInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Article\\GetListByAuthor",
        "interface": false,
        "methods": [
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Article\\Model\\Author"
        ],
        "parents": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 1,
        "effort": 3,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 3,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 8,
        "loc": 16,
        "lloc": 8,
        "mi": 121.28,
        "mIwoC": 76.82,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Article\\GetById",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetByIdInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Article\\GetListByCategory",
        "interface": false,
        "methods": [
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Article\\Model\\Category"
        ],
        "parents": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 1,
        "effort": 3,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 3,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 8,
        "loc": 16,
        "lloc": 8,
        "mi": 121.28,
        "mIwoC": 76.82,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Article\\GetList",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetListInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Article\\Purchase\\PurchaseArticleByUser",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCurrentFundBalance",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Maghead\\Runtime\\Repo",
            "Article\\Model\\Article",
            "User\\Model\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 16,
        "volume": 160,
        "difficulty": 4.83,
        "effort": 773.33,
        "level": 0.21,
        "bugs": 0.05,
        "time": 43,
        "intelligentContent": 33.1,
        "number_operators": 11,
        "number_operands": 29,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 23,
        "loc": 57,
        "lloc": 34,
        "mi": 92.39,
        "mIwoC": 50.76,
        "commentWeight": 41.64,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 81.67,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 245,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Author\\GetById",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetByIdInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Interactor\\Author\\GetList",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Interactor\\GetListInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Article\\Purchase\\Status",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 19,
        "loc": 28,
        "lloc": 9,
        "mi": 119.44,
        "mIwoC": 71.59,
        "commentWeight": 47.85,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]